export const CATEGORIES_V1 = [
  "Money",
  "Style",
  "Relationships",
  "Cars",
  "Career",
  "Health & Fitness",
  "Family & Parenting",
  "Food",
  "Home & DIY",
  "Tech & Gadgets",
  "Travel",
  "School & College",
  "Movies",
  "Television",
  "Music",
  "Sports",
  "Nature & Animals",
  "Events & Activities",
  "Gifts",
  "Beauty & Wellness",
] as const;

export type Category = (typeof CATEGORIES_V1)[number];

export const CATEGORY_EMOJI: Record<Category, string> = {
  Money: "💵",
  Style: "👕",
  Relationships: "💬",
  Cars: "🚗",
  Career: "💼",
  "Health & Fitness": "🏋️",
  "Family & Parenting": "👨‍👩‍👧‍👦",
  Food: "🍽️",
  "Home & DIY": "🏠",
  "Tech & Gadgets": "📱",
  Travel: "✈️",
  "School & College": "🎓",
  Movies: "🎬",
  Television: "📺",
  Music: "🎵",
  Sports: "🏅",
  "Nature & Animals": "🌿",
  "Events & Activities": "🎉",
  Gifts: "🎁",
  "Beauty & Wellness": "💆",
};
